### ISSUE TITLE
Infinite loop in computeSourcePositions

### ISSUE THREAD

**Issue by scharf** [hypothesis/dom-text-mapper#12]
I have seen several times infinite loops in computeSourcePositions (on firefox):

https://github.com/hypothesis/dom-text-mapper/blob/master/src/dom_text_mapper.coffee#L583-L593

Looking at the code, I wonder how the loop is guaranteed to end: Unless `sc  is dc`, the loop runs forever, or am I missing something here?

**Comment by csillag** [comment]
I just cherry-picked @mitar's fixes (https://github.com/hypothesis/dom-text-mapper/commit/5bbdbd3163d3e9d95f62b65e6dc4cc995254d53b, https://github.com/hypothesis/dom-text-mapper/commit/846d6835315b5eee8d48723c3c19c10477d6669c and https://github.com/hypothesis/dom-text-mapper/commit/7372ca9a40bd5f1b6b087b118ede0c48c4a6440a), so I think this is solved now.

Thanks, @mitar.
